const flashcard = document.getElementById("flashcard");
const front = document.getElementById("front");
const back = document.getElementById("back");

const words = [
 { word: "a", meaning: "하나의" },
    { word: "about", meaning: "~에 대하여" },
    { word: "above", meaning: "~보다 위에" },
    { word: "academy", meaning: "학원" },
    { word: "accent", meaning: "말투" },
    { word: "accident", meaning: "사건" },
    { word: "across", meaning: "가로질러" },
    { word: "act", meaning: "행동하다" },
    { word: "add", meaning: "추가하다" },
    { word: "address", meaning: "주소" },
    { word: "adult", meaning: "어른" },
    { word: "adventure", meaning: "모험" },
    { word: "advise", meaning: "충고하다" },
    { word: "afraid", meaning: "두려워하여" },
    { word: "after", meaning: "나중에" },
    { word: "afternoon", meaning: "오후" },
    { word: "again", meaning: "다시" },
    { word: "against", meaning: "~에 반대하여" },
    { word: "age", meaning: "나이" },
    { word: "ago", meaning: "이전에" },
    { word: "agree", meaning: "동의하다" },
    { word: "ahead", meaning: "전방에" },
    { word: "air", meaning: "공기" },
    { word: "airplane", meaning: "비행기" },
    { word: "airline", meaning: "항공사" },
    { word: "airport", meaning: "공항" },
    { word: "all", meaning: "모든" },
    { word: "almost", meaning: "거의" },
    { word: "alone", meaning: "혼자" },
    { word: "along", meaning: "~을 따라" },
    { word: "aloud", meaning: "큰 소리로" },
    { word: "already", meaning: "이미" },
    { word: "alright", meaning: "좋은" },
    { word: "also", meaning: "또한" },
    { word: "always", meaning: "항상" },
    { word: "AM", meaning: "오전" },
    { word: "and", meaning: "그리고" },
    { word: "angel", meaning: "천사" },
    { word: "anger", meaning: "화난" },
    { word: "animal", meaning: "동물" },
    { word: "another", meaning: "또 하나의" },
    { word: "answer", meaning: "대답하다" },
    { word: "ant", meaning: "개미" },
    { word: "any", meaning: "어떤" },
    { word: "apple", meaning: "사과" },
    { word: "area", meaning: "지역" },
    { word: "arm", meaning: "팔" },
    { word: "around", meaning: "약" },
    { word: "arrive", meaning: "도착하다" },
    { word: "art", meaning: "예술" },
    { word: "as", meaning: "같이" },
    { word: "ask", meaning: "부탁하다" },
    { word: "at", meaning: "에" },
    { word: "aunt", meaning: "이모" },
    { word: "away", meaning: "멀리" },
    { word: "baby", meaning: "갓난 아기" },
    { word: "back", meaning: "등" },
    { word: "background", meaning: "배경" },
    { word: "bad", meaning: "나쁜" },
    { word: "bake", meaning: "굽다" },
    { word: "ball", meaning: "공" },
    { word: "balloon", meaning: "풍선" },
    { word: "band", meaning: "악단" },
    { word: "bank", meaning: "은행" },
    { word: "base", meaning: "기초" },
    { word: "baseball", meaning: "야구" },
    { word: "basic", meaning: "기본의" },
    { word: "basket", meaning: "바구니" },
    { word: "basketball", meaning: "농구" },
    { word: "bat", meaning: "방망이" },
    { word: "bath", meaning: "목욕" },
    { word: "bathroom", meaning: "욕실" },
    { word: "battery", meaning: "전지" },
    { word: "battle", meaning: "전투" },
    { word: "be", meaning: "~이다" },
    { word: "beach", meaning: "해안" },
    { word: "bean", meaning: "콩" },
    { word: "bear", meaning: "곰" },
    { word: "beauty", meaning: "아름다움" },
    { word: "because", meaning: "왜냐하면" },
    { word: "become", meaning: "~이 되다" },
    { word: "bed", meaning: "침대" },
    { word: "bedroom", meaning: "침실" },
    { word: "bee", meaning: "꿀벌" },
    { word: "beef", meaning: "쇠고기" },
    { word: "before", meaning: "앞에" },
    { word: "begin", meaning: "시작하다" },
    { word: "behind", meaning: "뒤에" },
    { word: "believe", meaning: "믿다" },
    { word: "bell", meaning: "종" },
    { word: "below", meaning: "아래에" },
    { word: "beside", meaning: "~의 곁에" },
    { word: "between", meaning: "사이에" },
    { word: "bicycle", meaning: "자전거" },
    { word: "big", meaning: "큰" },
    { word: "bill", meaning: "계산서" },
    { word: "bird", meaning: "새" },
    { word: "birth", meaning: "출생" },
    { word: "birthday", meaning: "생일" },
    { word: "bite", meaning: "물다" },
    { word: "black", meaning: "검은" },
    { word: "block", meaning: "덩어리" },
    { word: "blood", meaning: "피" },
    { word: "blue", meaning: "푸른" },
    { word: "board", meaning: "널판지" },
    { word: "boat", meaning: "배" },
    { word: "body", meaning: "신체" },
    { word: "bomb", meaning: "폭탄" },
    { word: "bone", meaning: "뼈" },
    { word: "book", meaning: "책" },
    { word: "boot", meaning: "장화" },
    { word: "borrow", meaning: "빌다" },
    { word: "boss", meaning: "사장" },
    { word: "both", meaning: "쌍방의" },
    { word: "bottle", meaning: "병" },
    { word: "bottom", meaning: "밑바닥" },
    { word: "bowl", meaning: "그릇" },
    { word: "boy", meaning: "소년" },
    { word: "brain", meaning: "뇌" },
    { word: "brake", meaning: "브레이크" },
    { word: "branch", meaning: "가지" },
    { word: "brand", meaning: "상표" },
    { word: "brave", meaning: "용감한" },
    { word: "bread", meaning: "빵" },
    { word: "break", meaning: "중단, 휴식" },
    { word: "breakfast", meaning: "아침밥" },
    { word: "bridge", meaning: "다리" },
    { word: "bright", meaning: "밝은" },
    { word: "bring", meaning: "가져오다" },
    { word: "brother", meaning: "형제" },
    { word: "brown", meaning: "갈색" },
    { word: "brush", meaning: "솔, 양치질하다" },
    { word: "bubble", meaning: "거품, 거품이 일다" },
    { word: "bug", meaning: "벌레" },
    { word: "build", meaning: "짓다" },
    { word: "burn", meaning: "불에 타다" },
    { word: "business", meaning: "직업" },
    { word: "busy", meaning: "바쁜" },
    { word: "but", meaning: "그러나" },
    { word: "button", meaning: "단추, 단추를 채우다" },
    { word: "buy", meaning: "사다" },
    { word: "by", meaning: "곁에, 의해" },
    { word: "cage", meaning: "새장" },
    { word: "calendar", meaning: "달력" },
    { word: "call", meaning: "부르다" },
    { word: "calm", meaning: "평온한" },
    { word: "can", meaning: "할 수 있다" },
    { word: "candy", meaning: "사탕과자" },
    { word: "cap", meaning: "모자" },
    { word: "captain", meaning: "우두머리" },
    { word: "car", meaning: "자동차" },
    { word: "care", meaning: "걱정" },
    { word: "carrot", meaning: "당근" },
    { word: "carry", meaning: "나르다" },
    { word: "cart", meaning: "카트" },
    { word: "case", meaning: "경우" },
    { word: "cash", meaning: "현금" },
    { word: "castle", meaning: "성" },
    { word: "cat", meaning: "고양이" },
    { word: "catch", meaning: "붙잡다" },
    { word: "certain", meaning: "확신하는" },
    { word: "chain", meaning: "사슬" },
    { word: "chair", meaning: "의자" },
    { word: "chance", meaning: "기회" },
    { word: "change", meaning: "변화" },
    { word: "cheap", meaning: "값싼" },
    { word: "check", meaning: "점검하다" },
    { word: "child", meaning: "아이" },
    { word: "choose", meaning: "고르다" },
    { word: "church", meaning: "교회" },
    { word: "cinema", meaning: "영화, 극장" },
    { word: "circle", meaning: "원" },
    { word: "city", meaning: "도시" },
    { word: "class", meaning: "수업, 계급" },
    { word: "classroom", meaning: "교실" },
    { word: "clean", meaning: "청소하다" },
    { word: "clear", meaning: "맑은" },
    { word: "clerk", meaning: "직원" },
    { word: "clever", meaning: "영리한" },
    { word: "climb", meaning: "기어 오르다" },
    { word: "clip", meaning: "가위로 자르다" },
    { word: "clock", meaning: "시계" },
    { word: "close", meaning: "닫다" },
    { word: "cloth", meaning: "천" },
    { word: "cloud", meaning: "구름" },
    { word: "club", meaning: "클럽" },
    { word: "coin", meaning: "화폐" },
    { word: "cold", meaning: "추운" },
    { word: "collect", meaning: "모으다" },
    { word: "college", meaning: "단과대학" },
    { word: "color", meaning: "색" },
    { word: "come", meaning: "오다" },
    { word: "comedy", meaning: "희극" },
    { word: "company", meaning: "회사" },
    { word: "concert", meaning: "연주회" },
    { word: "condition", meaning: "조건" },
    { word: "congratulate", meaning: "축하하다" },
    { word: "contest", meaning: "겨루다" },
    { word: "control", meaning: "조정, 통제" },
    { word: "cook", meaning: "요리하다 요리사" },
    { word: "cookie", meaning: "쿠키" },
    { word: "cool", meaning: "서늘한" },
    { word: "copy", meaning: "사본, 복사" },
    { word: "corner", meaning: "모퉁이" },
    { word: "cost", meaning: "가격" },
    { word: "cotton", meaning: "목화" },
    { word: "could", meaning: "할 수 있다" },
    { word: "country", meaning: "나라" },
    { word: "countryside", meaning: "시골" },
    { word: "couple", meaning: "한 쌍" },
    { word: "cousin", meaning: "사촌" },
    { word: "cover", meaning: "덮다" },
    { word: "cow", meaning: "암소" },
    { word: "crazy", meaning: "미친" },
    { word: "cross", meaning: "십자형" },
    { word: "crowd", meaning: "군중" },
    { word: "crown", meaning: "왕관" },
    { word: "cry", meaning: "소리치다" },
    { word: "culture", meaning: "문화" },
    { word: "curious", meaning: "호기심 많은" },
    { word: "curtain", meaning: "커튼" },
    { word: "customer", meaning: "고객" },
    { word: "cut", meaning: "베다" },
    { word: "cute", meaning: "귀여운" },
    { word: "cycle", meaning: "순환" },
    { word: "dad", meaning: "아버지" },
    { word: "dance", meaning: "춤" },
    { word: "danger", meaning: "위험" },
    { word: "dark", meaning: "어두운" },
    { word: "date", meaning: "날짜" },
    { word: "daughter", meaning: "딸" },
    { word: "day", meaning: "낮" },
    { word: "dead", meaning: "죽은" },
    { word: "deal", meaning: "거래" },
    { word: "dear", meaning: "친애하는" },
    { word: "death", meaning: "죽음" },
    { word: "debt", meaning: "부채" },
    { word: "decide", meaning: "결정하다" },
    { word: "deep", meaning: "깊은" },
    { word: "deer", meaning: "사슴" },
    { word: "degree", meaning: "학위" },
    { word: "deliver", meaning: "전달하다" },
    { word: "demand", meaning: "요구" },
    { word: "department", meaning: "부서" },
    { word: "depend", meaning: "의지하다" },
    { word: "desk", meaning: "책상" },
    { word: "destroy", meaning: "파괴하다" },
    { word: "develop", meaning: "발전시키다" },
    { word: "die", meaning: "죽다" },
    { word: "different", meaning: "다른" },
    { word: "difficult", meaning: "어려운" },
    { word: "dinner", meaning: "저녁식사" },
    { word: "dirty", meaning: "더러운" },
    { word: "discover", meaning: "발견하다" },
    { word: "discuss", meaning: "토론하다" },
    { word: "dish", meaning: "요리" },
    { word: "dive", meaning: "뛰어들다" },
    { word: "divide", meaning: "나누다" },
    { word: "do", meaning: "하다" },
    { word: "doctor", meaning: "의사" },
    { word: "dog", meaning: "개" },
    { word: "dollar", meaning: "달러" },
    { word: "door", meaning: "문" },
    { word: "double", meaning: "두 배의" },
    { word: "down", meaning: "아래로" },
    { word: "draw", meaning: "그리다" },
    { word: "dream", meaning: "꿈" },
    { word: "dress", meaning: "드레스" },
    { word: "drink", meaning: "마시다" },
    { word: "drive", meaning: "운전하다" },
    { word: "drop", meaning: "떨어뜨리다" },
    { word: "dry", meaning: "건조한" },
    { word: "duck", meaning: "오리" },
    { word: "during", meaning: "동안" },
    { word: "dust", meaning: "먼지" },
    { word: "duty", meaning: "의무" },
    { word: "each", meaning: "각각의" },
    { word: "eager", meaning: "열심인" },
    { word: "ear", meaning: "귀" },
    { word: "early", meaning: "일찍" },
    { word: "earn", meaning: "벌다" },
    { word: "earth", meaning: "지구" },
    { word: "east", meaning: "동쪽" },
    { word: "easy", meaning: "쉬운" },
    { word: "eat", meaning: "먹다" },
    { word: "edge", meaning: "가장자리" },
    { word: "educate", meaning: "교육하다" },
    { word: "egg", meaning: "달걀" },
    { word: "eight", meaning: "여덟" },
    { word: "eighteen", meaning: "십팔" },
    { word: "eighty", meaning: "팔십" },
    { word: "either", meaning: "어느 것이든" },
    { word: "elephant", meaning: "코끼리" },
    { word: "else", meaning: "다른" },
    { word: "empty", meaning: "빈" },
    { word: "end", meaning: "끝" },
    { word: "enemy", meaning: "적" },
    { word: "engine", meaning: "엔진" },
    { word: "enjoy", meaning: "즐기다" },
    { word: "enough", meaning: "충분한" },
    { word: "enter", meaning: "들어가다" },
    { word: "equal", meaning: "동등한" },
    { word: "erase", meaning: "지우다" },
    { word: "escape", meaning: "도망치다" },
    { word: "even", meaning: "심지어" },
    { word: "evening", meaning: "저녁" },
    { word: "ever", meaning: "언제나" },
    { word: "every", meaning: "모든" },
    { word: "everyone", meaning: "모두" },
    { word: "everything", meaning: "모든 것" },
    { word: "exact", meaning: "정확한" },
    { word: "except", meaning: "제외하고" },
    { word: "excite", meaning: "흥분시키다" },
    { word: "exercise", meaning: "운동" },
    { word: "exist", meaning: "존재하다" },
    { word: "expect", meaning: "기대하다" },
    { word: "expensive", meaning: "비싼" },
    { word: "explain", meaning: "설명하다" },
    { word: "eye", meaning: "눈" },
    { word: "face", meaning: "얼굴" },
    { word: "fact", meaning: "사실" },
    { word: "factory", meaning: "공장" },
    { word: "fail", meaning: "실패하다" },
    { word: "fair", meaning: "공평한" },
    { word: "fall", meaning: "떨어지다" },
    { word: "family", meaning: "가족" },
    { word: "famous", meaning: "유명한" },
    { word: "fan", meaning: "부채" },
    { word: "far", meaning: "멀리" },
    { word: "farm", meaning: "농장" },
    { word: "farmer", meaning: "농부" },
    { word: "fast", meaning: "빠른" },
    { word: "fat", meaning: "지방" },
    { word: "father", meaning: "아버지" },
    { word: "fault", meaning: "잘못" },
    { word: "fear", meaning: "두려움" },
    { word: "feed", meaning: "먹이다" },
    { word: "feel", meaning: "느끼다" },
    { word: "female", meaning: "여성의" },
    { word: "fence", meaning: "울타리" },
    { word: "fever", meaning: "열" },
    { word: "few", meaning: "소수의" },
    { word: "field", meaning: "농장" },
    { word: "fifteen", meaning: "십오" },
    { word: "fifty", meaning: "오십" },
    { word: "fight", meaning: "싸움" },
    { word: "fill", meaning: "채우다" },
    { word: "film", meaning: "영화" },
    { word: "find", meaning: "찾다" },
    { word: "fine", meaning: "미세한" },
    { word: "finger", meaning: "손가락" },
    { word: "finish", meaning: "끝나다" },
    { word: "fire", meaning: "불" },
    { word: "first", meaning: "첫 번째" },
    { word: "fish", meaning: "물고기" },
    { word: "fit", meaning: "맞다" },
    { word: "five", meaning: "다섯" },
    { word: "fix", meaning: "수리하다" },
    { word: "flag", meaning: "깃발" },
    { word: "flat", meaning: "평평한" },
    { word: "flee", meaning: "도망가다" },
    { word: "float", meaning: "떠다니다" },
    { word: "floor", meaning: "바닥" },
    { word: "flower", meaning: "꽃" },
    { word: "fly", meaning: "날다" },
    { word: "fold", meaning: "접다" },
    { word: "follow", meaning: "따라가다" },
    { word: "food", meaning: "음식" },
    { word: "fool", meaning: "바보" },
    { word: "foot", meaning: "발" },
    { word: "football", meaning: "축구" },
    { word: "for", meaning: "~을 위해" },
    { word: "force", meaning: "힘" },
    { word: "foreign", meaning: "외국의" },
    { word: "forest", meaning: "숲" },
    { word: "forget", meaning: "잊다" },
    { word: "forgive", meaning: "용서하다" },
    { word: "fork", meaning: "포크" },
    { word: "form", meaning: "형태" },
    { word: "fortune", meaning: "재산" },
    { word: "forward", meaning: "앞으로" },
    { word: "four", meaning: "넷" },
    { word: "fourteen", meaning: "십사" },
    { word: "fox", meaning: "여우" },
    { word: "free", meaning: "자유로운" },
    { word: "freedom", meaning: "자유" },
    { word: "freeze", meaning: "얼다" },
    { word: "fresh", meaning: "신선한" },
    { word: "friend", meaning: "친구" },
    { word: "frog", meaning: "개구리" },
    { word: "from", meaning: "~부터" },
    { word: "front", meaning: "앞" },
    { word: "fruit", meaning: "과일" },
    { word: "fuel", meaning: "연료" },
    { word: "full", meaning: "가득 찬" },
    { word: "fun", meaning: "즐거움" },
    { word: "funny", meaning: "웃긴" },
    { word: "future", meaning: "미래" },
    { word: "game", meaning: "경기" },
    { word: "garden", meaning: "정원" },
    { word: "gas", meaning: "가스" },
    { word: "gate", meaning: "게이트" },
    { word: "gather", meaning: "모으다" },
    { word: "gave", meaning: "주었다" },
    { word: "general", meaning: "일반적인" },
    { word: "gentle", meaning: "온화한" },
    { word: "get", meaning: "얻다" },
    { word: "gift", meaning: "선물" },
    { word: "girl", meaning: "소녀" },
    { word: "give", meaning: "주다" },
    { word: "glad", meaning: "기쁜" },
    { word: "glass", meaning: "유리" },
    { word: "glove", meaning: "장갑" },
    { word: "go", meaning: "가다" },
    { word: "goal", meaning: "목표" },
    { word: "God", meaning: "신" },
    { word: "gold", meaning: "금" },
    { word: "good", meaning: "좋은" },
    { word: "goodbye", meaning: "안녕" },
    { word: "goose", meaning: "거위" },
    { word: "government", meaning: "정부" },
    { word: "grade", meaning: "등급" },
    { word: "grand", meaning: "위엄 있는" },
    { word: "grandmother", meaning: "할머니" },
    { word: "grape", meaning: "포도" },
    { word: "grass", meaning: "잔디" },
    { word: "grateful", meaning: "고마워하는" },
    { word: "grave", meaning: "무덤" },
    { word: "gray", meaning: "회색의" },
    { word: "great", meaning: "멋진" },
    { word: "green", meaning: "녹색" },
    { word: "greet", meaning: "인사하다" },
    { word: "ground", meaning: "땅" },
    { word: "group", meaning: "집단" },
    { word: "grow", meaning: "성장하다" },
    { word: "guess", meaning: "추측하다" },
    { word: "guest", meaning: "손님" },
    { word: "guide", meaning: "안내하다" },
    { word: "guilty", meaning: "유죄의" },
    { word: "gun", meaning: "총" },
    { word: "hair", meaning: "머리카락" },
    { word: "half", meaning: "반" },
    { word: "hall", meaning: "홀" },
    { word: "ham", meaning: "햄" },
    { word: "hammer", meaning: "망치" },
    { word: "hand", meaning: "손" },
    { word: "handkerchief", meaning: "손수건" },
    { word: "handle", meaning: "손잡이" },
    { word: "hang", meaning: "걸다" },
    { word: "happen", meaning: "일어나다" },
    { word: "happy", meaning: "행복한" },
    { word: "hard", meaning: "딱한" },
    { word: "hat", meaning: "모자" },
    { word: "hate", meaning: "미움" },
    { word: "have", meaning: "가지다" },
    { word: "he", meaning: "그" },
    { word: "head", meaning: "머리" },
    { word: "headache", meaning: "두통" },
    { word: "heal", meaning: "치유하다" },
    { word: "health", meaning: "건강" },
    { word: "hear", meaning: "듣다" },
    { word: "heart", meaning: "심장" },
    { word: "heat", meaning: "열" },
    { word: "heavy", meaning: "무거운" },
    { word: "heel", meaning: "뒷굽" },
    { word: "height", meaning: "신장" },
    { word: "hell", meaning: "지옥" },
    { word: "hello", meaning: "안녕하세요" },
    { word: "help", meaning: "도움" },
    { word: "hen", meaning: "암탉" },
    { word: "her", meaning: "그녀의" },
    { word: "here", meaning: "여기" },
    { word: "hers", meaning: "그녀의 것" },
    { word: "herself", meaning: "그녀 자신" },
    { word: "hide", meaning: "숨다" },
    { word: "high", meaning: "높은" },
    { word: "hill", meaning: "언덕" },
    { word: "him", meaning: "그를" },
    { word: "himself", meaning: "그 자신" },
    { word: "his", meaning: "그의" },
    { word: "history", meaning: "역사" },
    { word: "hit", meaning: "때리다" },
    { word: "hobby", meaning: "취미" },
    { word: "hold", meaning: "잡다" },
    { word: "hole", meaning: "구멍" },
    { word: "holiday", meaning: "휴일" },
    { word: "holy", meaning: "신성한" },
    { word: "home", meaning: "집" },
    { word: "honest", meaning: "정직한" },
    { word: "honey", meaning: "꿀" },
    { word: "hook", meaning: "갈고리" },
    { word: "hope", meaning: "희망" },
    { word: "horse", meaning: "말" },
    { word: "hospital", meaning: "병원" },
    { word: "hot", meaning: "뜨거운" },
    { word: "hotel", meaning: "호텔" },
    { word: "hour", meaning: "시간" },
    { word: "house", meaning: "집" },
    { word: "how", meaning: "어떻게" },
    { word: "however", meaning: "그러나" },
    { word: "huge", meaning: "거대한" },
    { word: "human", meaning: "인간" },
    { word: "hunt", meaning: "사냥하다" },
    { word: "hurry", meaning: "서두르다" },
    { word: "hurt", meaning: "다치게 하다" },
    { word: "husband", meaning: "남편" },
    { word: "I", meaning: "나" },
    { word: "ice", meaning: "얼음" },
    { word: "idea", meaning: "생각" },
    { word: "if", meaning: "~이라면" },
    { word: "ignore", meaning: "무시하다" },
    { word: "ill", meaning: "병든" },
    { word: "imagine", meaning: "상상하다" },
    { word: "important", meaning: "중요한" },
    { word: "improve", meaning: "개선하다" },
    { word: "in", meaning: "안에" },
    { word: "include", meaning: "포함하다" },
    { word: "income", meaning: "소득" },
    { word: "indeed", meaning: "정말로" },
    { word: "Indian", meaning: "인도의" },
    { word: "inside", meaning: "안에" },
    { word: "instead", meaning: "대신에" },
    { word: "intend", meaning: "의도하다" },
    { word: "interest", meaning: "흥미" },
    { word: "into", meaning: "~로" },
    { word: "invite", meaning: "초대하다" },
    { word: "iron", meaning: "철" },
    { word: "island", meaning: "섬" },
    { word: "it", meaning: "그것" },
    { word: "its", meaning: "그것의" },
    { word: "itself", meaning: "그 자체" },
    { word: "jacket", meaning: "재킷" },
    { word: "jail", meaning: "감옥" },
    { word: "jealous", meaning: "질투하는" },
    { word: "jelly", meaning: "젤리" },
    { word: "jewel", meaning: "보석" },
    { word: "job", meaning: "일" },
    { word: "join", meaning: "가입하다" },
    { word: "joke", meaning: "농담" },
    { word: "joy", meaning: "기쁨" },
    { word: "judge", meaning: "판사" },
    { word: "juice", meaning: "주스" },
    { word: "jump", meaning: "뛰다" },
    { word: "just", meaning: "딱" },
    { word: "keep", meaning: "유지하다" },
    { word: "key", meaning: "열쇠" },
    { word: "kick", meaning: "차다" },
    { word: "kid", meaning: "아이" },
    { word: "kill", meaning: "죽이다" },
    { word: "kind", meaning: "종류" },
    { word: "king", meaning: "왕" },
    { word: "kiss", meaning: "키스" },
    { word: "kitchen", meaning: "주방" },
    { word: "knee", meaning: "무릎" },
    { word: "knife", meaning: "칼" },
    { word: "knock", meaning: "노크하다" },
    { word: "know", meaning: "알다" },
    { word: "ladder", meaning: "사다리" },
    { word: "lady", meaning: "아가씨" },
    { word: "lake", meaning: "호수" },
    { word: "lamp", meaning: "램프" },
    { word: "land", meaning: "땅" },
    { word: "language", meaning: "언어" },
    { word: "large", meaning: "큰" },
    { word: "last", meaning: "마지막의" },
    { word: "late", meaning: "늦은" },
    { word: "laugh", meaning: "웃다" },
    { word: "lazy", meaning: "게으른" },
    { word: "lead", meaning: "이끌다" },
    { word: "leaf", meaning: "잎" },
    { word: "learn", meaning: "배우다" },
    { word: "least", meaning: "적어도" },
    { word: "leave", meaning: "떠나다" },
    { word: "left", meaning: "왼쪽의" },
    { word: "leg", meaning: "다리" },
    { word: "lemon", meaning: "레몬" },
    { word: "less", meaning: "더 적은" },
    { word: "lesson", meaning: "교훈" },
    { word: "let", meaning: "허락하다" },
    { word: "letter", meaning: "편지" },
    { word: "library", meaning: "도서관" },
    { word: "lie", meaning: "거짓말" },
    { word: "life", meaning: "생활" },
    { word: "light", meaning: "빛" },
    { word: "like", meaning: "좋아하다" },
    { word: "lion", meaning: "사자" },
    { word: "lip", meaning: "입술" },
    { word: "list", meaning: "목록" },
    { word: "listen", meaning: "듣다" },
    { word: "little", meaning: "작은" },
    { word: "live", meaning: "살다" },
    { word: "lock", meaning: "잠그다" },
    { word: "lonely", meaning: "외로운" },
    { word: "long", meaning: "긴" },
    { word: "look", meaning: "보다" },
    { word: "lose", meaning: "잃다" },
    { word: "loud", meaning: "시끄러운" },
    { word: "love", meaning: "사랑" },
    { word: "low", meaning: "낮은" },
    { word: "luck", meaning: "행운" },
    { word: "lucky", meaning: "운이 좋은" },
    { word: "lunch", meaning: "점심" },
    { word: "machine", meaning: "기계" },
    { word: "mad", meaning: "미친" },
    { word: "magazine", meaning: "잡지" },
    { word: "mail", meaning: "우편물" },
    { word: "make", meaning: "만들다" },
    { word: "man", meaning: "남자" },
    { word: "manage", meaning: "관리하다" },
    { word: "many", meaning: "많은" },
    { word: "map", meaning: "지도" },
    { word: "mark", meaning: "표시" },
    { word: "market", meaning: "시장" },
    { word: "marry", meaning: "결혼하다" },
    { word: "match", meaning: "경기" },
    { word: "material", meaning: "재료" },
    { word: "matter", meaning: "문제" },
    { word: "may", meaning: "할 수도 있다" },
    { word: "maybe", meaning: "아마" },
    { word: "me", meaning: "나를" },
    { word: "meal", meaning: "식사" },
    { word: "mean", meaning: "의미하다" },
    { word: "measure", meaning: "측정하다" },
    { word: "meat", meaning: "고기" },
    { word: "medicine", meaning: "약" },
    { word: "meet", meaning: "만나다" },
    { word: "melt", meaning: "녹다" },
    { word: "member", meaning: "회원" },
    { word: "mention", meaning: "언급하다" },
    { word: "menu", meaning: "메뉴" },
    { word: "merry", meaning: "즐거운" },
    { word: "message", meaning: "메시지" },
    { word: "met", meaning: "만났다" },
    { word: "middle", meaning: "중간" },
    { word: "might", meaning: "~일지도 모른다" },
    { word: "mile", meaning: "마일" },
    { word: "milk", meaning: "우유" },
    { word: "mind", meaning: "마음" },
    { word: "mine", meaning: "내것" },
    { word: "minute", meaning: "분" },
    { word: "mirror", meaning: "거울" },
    { word: "miss", meaning: "그리워하다" },
    { word: "mistake", meaning: "실수" },
    { word: "mix", meaning: "섞다" },
    { word: "model", meaning: "모델" },
    { word: "modern", meaning: "현대의" },
    { word: "moment", meaning: "순간" },
    { word: "Monday", meaning: "월요일" },
    { word: "money", meaning: "돈" },
    { word: "monkey", meaning: "원숭이" },
    { word: "month", meaning: "달" },
    { word: "moon", meaning: "달" },
    { word: "more", meaning: "더 많은" },
    { word: "morning", meaning: "아침" },
    { word: "most", meaning: "가장 많은" },
    { word: "mother", meaning: "어머니" },
    { word: "mountain", meaning: "산" },
    { word: "mouse", meaning: "쥐" },
    { word: "mouth", meaning: "입" },
    { word: "move", meaning: "움직이다" },
    { word: "movie", meaning: "영화" },
    { word: "Mr.", meaning: "아저씨" },
    { word: "Mrs.", meaning: "아주머니" },
    { word: "much", meaning: "많은" },
    { word: "music", meaning: "음악" },
    { word: "must", meaning: "해야 한다" },
    { word: "my", meaning: "나의" },
    { word: "myself", meaning: "내 자신" },
    { word: "nail", meaning: "손톱" },
    { word: "name", meaning: "이름" },
    { word: "napkin", meaning: "냅킨" },
    { word: "narrow", meaning: "좁은" },
    { word: "nation", meaning: "국가" },
    { word: "nature", meaning: "자연" },
    { word: "near", meaning: "가까운" },
    { word: "neck", meaning: "목" },
    { word: "need", meaning: "필요" },
    { word: "needle", meaning: "바늘" },
    { word: "negative", meaning: "부정적인" },
    { word: "neighbor", meaning: "이웃" },
    { word: "neither", meaning: "둘 다 ~않다" },
    { word: "nephew", meaning: "조카" },
    { word: "nerve", meaning: "신경" },
    { word: "nest", meaning: "둥지" },
    { word: "net", meaning: "그물" },
    { word: "never", meaning: "결코 ~않다" },
    { word: "new", meaning: "새로운" },
    { word: "news", meaning: "뉴스" },
    { word: "newspaper", meaning: "신문" },
    { word: "next", meaning: "다음의" },
    { word: "nice", meaning: "좋은" },
    { word: "night", meaning: "밤" },
    { word: "nine", meaning: "아홉" },
    { word: "no", meaning: "아니" },
    { word: "noble", meaning: "고귀한" },
    { word: "nobody", meaning: "아무도 ~않다" },
    { word: "nod", meaning: "끄덕이다" },
    { word: "noise", meaning: "소음" },
    { word: "none", meaning: "어느 것도 ~않다" },
    { word: "noon", meaning: "정오" },
    { word: "nor", meaning: "또한 ~않다" },
    { word: "north", meaning: "북쪽" },
    { word: "nose", meaning: "코" },
    { word: "not", meaning: "~아니다" },
    { word: "note", meaning: "노트" },
    { word: "nothing", meaning: "아무것도" },
    { word: "notice", meaning: "주목" },
    { word: "noun", meaning: "명사" },
    { word: "now", meaning: "지금" },
    { word: "nowhere", meaning: "어디에도 ~않다" },
    { word: "number", meaning: "숫자" },
    { word: "nurse", meaning: "간호사" },
    { word: "nut", meaning: "견과류" },
    { word: "o'clock", meaning: "~시" },
    { word: "ocean", meaning: "바다" },
    { word: "October", meaning: "10월" },
    { word: "of", meaning: "~의" },
    { word: "off", meaning: "떨어져" },
    { word: "offer", meaning: "제공하다" },
    { word: "office", meaning: "사무실" },
    { word: "often", meaning: "자주" },
    { word: "oil", meaning: "기름" },
    { word: "old", meaning: "노인" },
    { word: "on", meaning: "~에" },
    { word: "once", meaning: "한번" },
    { word: "one", meaning: "한 개의" },
    { word: "only", meaning: "오직" },
    { word: "open", meaning: "열다" },
    { word: "opinion", meaning: "의견" },
    { word: "opposite", meaning: "반대" },
    { word: "or", meaning: "~또는" },
    { word: "orange", meaning: "주황색" },
    { word: "order", meaning: "주문" },
    { word: "other", meaning: "다른" },
    { word: "our", meaning: "우리의" },
    { word: "ours", meaning: "우리의 것" },
    { word: "ourselves", meaning: "우리 자신" },
    { word: "out", meaning: "밖으로" },
    { word: "outside", meaning: "밖에" },
    { word: "over", meaning: "위로" },
    { word: "own", meaning: "자신의" },
    { word: "owner", meaning: "소유주" },
    { word: "page", meaning: "페이지" },
    { word: "pain", meaning: "고통" },
    { word: "paint", meaning: "페인트" },
    { word: "pair", meaning: "한 쌍" },
    { word: "pale", meaning: "창백한" },
    { word: "pan", meaning: "팬" },
    { word: "paper", meaning: "종이" },
    { word: "parcel", meaning: "소포" },
    { word: "pardon", meaning: "용서하다" },
    { word: "parent", meaning: "부모" },
    { word: "park", meaning: "공원" },
    { word: "part", meaning: "부분" },
    { word: "partner", meaning: "파트너" },
    { word: "party", meaning: "파티" },
    { word: "pass", meaning: "통과하다" },
    { word: "past", meaning: "지나간" },
    { word: "path", meaning: "길" },
    { word: "pay", meaning: "지불하다" },
    { word: "peace", meaning: "평화" },
    { word: "pen", meaning: "펜" },
    { word: "pencil", meaning: "연필" },
    { word: "penny", meaning: "페니" },
    { word: "people", meaning: "사람들" },
    { word: "pepper", meaning: "후추" },
    { word: "perfect", meaning: "완벽한" },
    { word: "perhaps", meaning: "아마도" },
    { word: "person", meaning: "사람" },
    { word: "pet", meaning: "애완동물" },
    { word: "phone", meaning: "전화" },
    { word: "photo", meaning: "사진" },
    { word: "pick", meaning: "고르다" },
    { word: "picture", meaning: "사진" },
    { word: "piece", meaning: "조각" },
    { word: "pig", meaning: "돼지" },
    { word: "pile", meaning: "무더기" },
    { word: "pin", meaning: "핀" },
    { word: "pink", meaning: "분홍색" },
    { word: "pint", meaning: "파인트" },
    { word: "pipe", meaning: "파이프" },
    { word: "pity", meaning: "애석함" },
    { word: "place", meaning: "장소" },
    { word: "plan", meaning: "계획" },
    { word: "plant", meaning: "식물" },
    { word: "plate", meaning: "접시" },
    { word: "play", meaning: "놀다" },
    { word: "please", meaning: "부탁드립니다" },
    { word: "pleasure", meaning: "즐거움" },
    { word: "plenty", meaning: "충분한" },
    { word: "pocket", meaning: "주머니" },
    { word: "point", meaning: "지점" },
    { word: "poison", meaning: "독" },
    { word: "police", meaning: "경찰" },
    { word: "polite", meaning: "정중한" },
    { word: "pond", meaning: "연못" },
    { word: "pool", meaning: "풀" },
    { word: "poor", meaning: "가난한" },
    { word: "popular", meaning: "인기 있는" },
    { word: "position", meaning: "위치" },
    { word: "possible", meaning: "가능한" },
    { word: "post", meaning: "우편물" },
    { word: "pot", meaning: "냄비" },
    { word: "potato", meaning: "감자" },
    { word: "pour", meaning: "따르다" },
    { word: "powder", meaning: "가루" },
    { word: "power", meaning: "힘" },
    { word: "powerful", meaning: "강력한" },
    { word: "practical", meaning: "실용적인" },
    { word: "praise", meaning: "칭찬" },
    { word: "pray", meaning: "기도하다" },
    { word: "prayer", meaning: "기도" },
    { word: "prepare", meaning: "준비하다" },
    { word: "present", meaning: "현재" },
    { word: "press", meaning: "누르다" },
    { word: "pretty", meaning: "예쁜" },
    { word: "prevent", meaning: "막다" },
    { word: "price", meaning: "가격" },
    { word: "print", meaning: "인쇄하다" },
    { word: "prison", meaning: "감옥" },
    { word: "private", meaning: "사적인" },
    { word: "prize", meaning: "상" },
    { word: "probable", meaning: "아마도" },
    { word: "problem", meaning: "문제" },
    { word: "promise", meaning: "약속" },
    { word: "proper", meaning: "적절한" },
    { word: "protect", meaning: "보호하다" },
    { word: "proud", meaning: "자랑스러운" },
    { word: "provide", meaning: "제공하다" },
    { word: "public", meaning: "공공의" },
    { word: "pull", meaning: "당기다" },
    { word: "pump", meaning: "펌프" },
    { word: "punish", meaning: "벌하다" },
    { word: "puppy", meaning: "강아지" },
    { word: "pure", meaning: "순수한" },
    { word: "purple", meaning: "보라색" },
    { word: "purpose", meaning: "목적" },
    { word: "push", meaning: "밀다" },
    { word: "put", meaning: "놓다" },
    { word: "quarter", meaning: "사분의 하나" },
    { word: "queen", meaning: "여왕" },
    { word: "question", meaning: "질문" },
    { word: "quick", meaning: "빠른" },
    { word: "quiet", meaning: "조용한" },
    { word: "quite", meaning: "아주" },
    { word: "rabbit", meaning: "토끼" },
    { word: "race", meaning: "경주" },
    { word: "radio", meaning: "라디오" },
    { word: "rail", meaning: "철로" },
    { word: "rain", meaning: "비" },
    { word: "rainy", meaning: "비 오는" },
    { word: "raise", meaning: "올리다" },
    { word: "range", meaning: "범위" },
    { word: "rat", meaning: "쥐" },
    { word: "rather", meaning: "오히려" },
    { word: "reach", meaning: "도달하다" },
    { word: "read", meaning: "읽다" },
    { word: "ready", meaning: "준비된" },
    { word: "real", meaning: "진짜의" },
    { word: "really", meaning: "진짜로" },
    { word: "reason", meaning: "이유" },
    { word: "receive", meaning: "받다" },
    { word: "record", meaning: "기록" },
    { word: "red", meaning: "빨간" },
    { word: "reduce", meaning: "줄이다" },
    { word: "reindeer", meaning: "순록" },
    { word: "refresh", meaning: "새롭게 하다" },
    { word: "refrigerator", meaning: "냉장고" },
    { word: "regard", meaning: "고려하다" },
    { word: "region", meaning: "지역" },
    { word: "regular", meaning: "정기적인" },
    { word: "reject", meaning: "거부하다" },
    { word: "relax", meaning: "휴식하다" },
    { word: "release", meaning: "석방하다" },
    { word: "remain", meaning: "남아 있다" },
    { word: "remember", meaning: "기억하다" },
    { word: "remind", meaning: "기억시키다" },
    { word: "remove", meaning: "제거하다" },
    { word: "repeat", meaning: "반복하다" },
    { word: "replace", meaning: "대체하다" },
    { word: "reply", meaning: "답장하다" },
    { word: "report", meaning: "보고서" },
    { word: "represent", meaning: "대표하다" },
    { word: "require", meaning: "요구하다" },
    { word: "rescue", meaning: "구조하다" },
    { word: "research", meaning: "연구" },
    { word: "rest", meaning: "나머지" },
    { word: "restaurant", meaning: "레스토랑" },
    { word: "result", meaning: "결과" },
    { word: "return", meaning: "돌아가다" },
    { word: "review", meaning: "리뷰" },
    { word: "reward", meaning: "보상" },
    { word: "rice", meaning: "쌀" },
    { word: "rich", meaning: "부자" },
    { word: "ride", meaning: "타다" },
    { word: "right", meaning: "옳은" },
    { word: "ring", meaning: "반지" },
    { word: "rise", meaning: "일어나다" },
    { word: "river", meaning: "강" },
    { word: "road", meaning: "길" },
    { word: "rob", meaning: "털다" },
    { word: "rock", meaning: "바위" },
    { word: "rocket", meaning: "로켓" },
    { word: "roof", meaning: "지붕" },
    { word: "room", meaning: "방" },
    { word: "rope", meaning: "로프" },
    { word: "rose", meaning: "장미" },
    { word: "rough", meaning: "거친" },
    { word: "round", meaning: "둥근" },
    { word: "row", meaning: "열" },
    { word: "royal", meaning: "왕실의" },
    { word: "rub", meaning: "비비다" },
    { word: "rubber", meaning: "고무" },
    { word: "rude", meaning: "무례한" },
    { word: "rug", meaning: "양탄자" },
    { word: "ruin", meaning: "파멸" },
    { word: "rule", meaning: "규칙" },
    { word: "run", meaning: "달리다" },
    { word: "rush", meaning: "돌진하다" },
    { word: "sad", meaning: "슬픈" },
    { word: "safe", meaning: "안전한" },
    { word: "sail", meaning: "항해하다" },
    { word: "sailor", meaning: "선원" },
    { word: "salt", meaning: "소금" },
    { word: "same", meaning: "같은" },
    { word: "sand", meaning: "모래" },
    { word: "sandwich", meaning: "샌드위치" },
    { word: "satisfaction", meaning: "만족" },
    { word: "satisfy", meaning: "만족시키다" },
    { word: "Saturday", meaning: "토요일" },
    { word: "save", meaning: "저장하다" },
    { word: "saw", meaning: "톱" },
    { word: "say", meaning: "말하다" },
    { word: "scale", meaning: "규모" },
    { word: "school", meaning: "학교" },
    { word: "scissors", meaning: "가위" },
    { word: "score", meaning: "점수" },
    { word: "scrape", meaning: "긁다" },
    { word: "scratch", meaning: "긁다" },
    { word: "scream", meaning: "소리치다" },
    { word: "sea", meaning: "바다" },
    { word: "seal", meaning: "물개" },
    { word: "search", meaning: "찾다" },
    { word: "season", meaning: "계절" },
    { word: "seat", meaning: "의자" },
    { word: "second", meaning: "둘째" },
    { word: "secret", meaning: "비밀" },
    { word: "see", meaning: "보다" },
    { word: "seed", meaning: "씨" },
    { word: "seem", meaning: "것 같다" },
    { word: "seldom", meaning: "드물게" },
    { word: "select", meaning: "선택하다" },
    { word: "self", meaning: "자기" },
    { word: "selfish", meaning: "이기적인" },
    { word: "sell", meaning: "팔다" },
    { word: "send", meaning: "보내다" },
    { word: "sense", meaning: "감각" },
    { word: "sentence", meaning: "문장" },
    { word: "separate", meaning: "분리된" },
    { word: "September", meaning: "9월" },
    { word: "serious", meaning: "진지한" },
    { word: "serve", meaning: "제공하다" },
    { word: "service", meaning: "서비스" },
    { word: "set", meaning: "설치하다" },
    { word: "settle", meaning: "정착하다" },
    { word: "several", meaning: "몇몇" },
    { word: "sew", meaning: "바느질하다" },
    { word: "shade", meaning: "그늘" },
    { word: "shadow", meaning: "그림자" },
    { word: "shake", meaning: "흔들다" },
    { word: "shame", meaning: "부끄러움" },
    { word: "shape", meaning: "모양" },
    { word: "share", meaning: "공유하다" },
    { word: "sharp", meaning: "날카로운" },
    { word: "shave", meaning: "면도하다" },
    { word: "she", meaning: "그녀" },
    { word: "sheep", meaning: "양" },
    { word: "sheet", meaning: "시트" },
    { word: "shelf", meaning: "선반" },
    { word: "shell", meaning: "껍질" },
    { word: "shelter", meaning: "피난처" },
    { word: "shine", meaning: "빛나다" },
    { word: "ship", meaning: "배" },
    { word: "shirt", meaning: "셔츠" },
    { word: "shock", meaning: "충격" },
    { word: "shoot", meaning: "쏘다" },
    { word: "shop", meaning: "가게" },
    { word: "shore", meaning: "해안" },
    { word: "short", meaning: "짧은" },
    { word: "should", meaning: "~할 것이다" },
    { word: "shoulder", meaning: "어깨" },
    { word: "shout", meaning: "외치다" },
    { word: "show", meaning: "보여주다" },
    { word: "shut", meaning: "닫다" },
    { word: "shy", meaning: "부끄러운" },
    { word: "sick", meaning: "아픈" },
    { word: "side", meaning: "측면" },
    { word: "sight", meaning: "광경" },
    { word: "sign", meaning: "표시" },
    { word: "silence", meaning: "침묵" },
    { word: "silent", meaning: "침묵하는" },
    { word: "silk", meaning: "비단" },
    { word: "silly", meaning: "바보 같은" },
    { word: "silver", meaning: "은" },
    { word: "similar", meaning: "비슷한" },
    { word: "simple", meaning: "간단한" },
    { word: "since", meaning: "이후" },
    { word: "sing", meaning: "노래하다" },
    { word: "single", meaning: "단일의" },
    { word: "sink", meaning: "물살" },
    { word: "sir", meaning: "선생님" },
    { word: "sister", meaning: "자매" },
    { word: "sit", meaning: "앉다" },
    { word: "situation", meaning: "상황" },
    { word: "size", meaning: "크기" },
    { word: "skill", meaning: "기술" },
    { word: "skin", meaning: "피부" },
    { word: "skirt", meaning: "치마" },
    { word: "sky", meaning: "하늘" },
    { word: "slave", meaning: "노예" },
    { word: "sleep", meaning: "자다" },
    { word: "sleeve", meaning: "소매" },
    { word: "slight", meaning: "약간의" },
    { word: "slip", meaning: "미끄러지다" },
    { word: "slope", meaning: "경사" },
    { word: "slow", meaning: "느린" },
    { word: "small", meaning: "작은" },
    { word: "smash", meaning: "부수다" },
    { word: "smell", meaning: "냄새" },
    { word: "smile", meaning: "미소" },
    { word: "smoke", meaning: "연기" },
    { word: "smooth", meaning: "매끄러운" },
    { word: "snake", meaning: "뱀" },
    { word: "sneeze", meaning: "재채기" },
    { word: "snow", meaning: "눈" },
    { word: "so", meaning: "그래서" },
    { word: "soap", meaning: "비누" },
    { word: "society", meaning: "사회" },
    { word: "sock", meaning: "양말" },
    { word: "soft", meaning: "부드러운" },
    { word: "soil", meaning: "흙" },
    { word: "soldier", meaning: "군인" },
    { word: "solid", meaning: "단단한" },
    { word: "solve", meaning: "해결하다" },
    { word: "some", meaning: "어떤" },
    { word: "somebody", meaning: "누군가" },
    { word: "somehow", meaning: "어떻게" },
    { word: "someone", meaning: "누군가" },
    { word: "something", meaning: "무엇인가" },
    { word: "sometimes", meaning: "가끔" },
    { word: "somewhere", meaning: "어딘가" },
    { word: "son", meaning: "아들" },
    { word: "song", meaning: "노래" },
    { word: "soon", meaning: "곧" },
    { word: "sore", meaning: "아픈" },
    { word: "sorry", meaning: "미안한" },
    { word: "sort", meaning: "종류" },
    { word: "soul", meaning: "영혼" },
    { word: "sound", meaning: "소리" },
    { word: "soup", meaning: "스프" },
    { word: "sour", meaning: "시큼한" },
    { word: "south", meaning: "남쪽" },
    { word: "space", meaning: "공간" },
    { word: "speak", meaning: "말하다" },
    { word: "special", meaning: "특별한" },
    { word: "speed", meaning: "속도" },
    { word: "spell", meaning: "주문" },
    { word: "spend", meaning: "소비하다" },
    { word: "spill", meaning: "엎지르다" },
    { word: "spin", meaning: "돌다" },
    { word: "spirit", meaning: "정신" },
    { word: "spite", meaning: "악의" },
    { word: "split", meaning: "나누다" },
    { word: "spoil", meaning: "망치다" },
    { word: "spoon", meaning: "숟가락" },
    { word: "sport", meaning: "스포츠" },
    { word: "spot", meaning: "장소" },
    { word: "spread", meaning: "퍼뜨리다" },
    { word: "spring", meaning: "봄" },
    { word: "square", meaning: "정사각형" },
    { word: "stable", meaning: "안정된" },
    { word: "staff", meaning: "직원" },
    { word: "stage", meaning: "단계" },
    { word: "stair", meaning: "계단" },
    { word: "stamp", meaning: "우표" },
    { word: "stand", meaning: "서다" },
    { word: "star", meaning: "별" },
    { word: "start", meaning: "시작하다" },
    { word: "state", meaning: "상태" },
    { word: "station", meaning: "역" },
    { word: "stay", meaning: "머무르다" },
    { word: "steady", meaning: "확실한" },
    { word: "steam", meaning: "증기" },
    { word: "steel", meaning: "강철" },
    { word: "steep", meaning: "가파른" },
    { word: "steer", meaning: "조종하다" },
    { word: "stem", meaning: "줄기" },
    { word: "step", meaning: "단계" },
    { word: "stick", meaning: "막대기" },
    { word: "sticky", meaning: "끈적끈적한" },
    { word: "stiff", meaning: "뻣뻣한" },
    { word: "still", meaning: "아직" },
    { word: "stir", meaning: "섞다" },
    { word: "stone", meaning: "돌" },
    { word: "stood", meaning: "서다" },
    { word: "stop", meaning: "멈추다" },
    { word: "store", meaning: "가게" },
    { word: "stove", meaning: "난로" },
    { word: "straight", meaning: "곧은" },
    { word: "strange", meaning: "이상한" },
    { word: "stranger", meaning: "낯선 사람" },
    { word: "strap", meaning: "줄" },
    { word: "straw", meaning: "짚" },
    { word: "strawberry", meaning: "딸기" },
    { word: "stream", meaning: "시냇물" },
    { word: "street", meaning: "거리" },
    { word: "stretch", meaning: "늘리다" },
    { word: "strike", meaning: "타격" },
    { word: "string", meaning: "끈" },
    { word: "strip", meaning: "빼다" },
    { word: "stripe", meaning: "줄무늬" },
    { word: "strong", meaning: "강한" },
    { word: "struggle", meaning: "노력" },
    { word: "student", meaning: "학생" },
    { word: "study", meaning: "공부" },
    { word: "stuff", meaning: "물건" },
    { word: "stupid", meaning: "멍청한" },
    { word: "subject", meaning: "주제" },
    { word: "substance", meaning: "물질" },
    { word: "success", meaning: "성공" },
    { word: "such", meaning: "그런" },
    { word: "sudden", meaning: "갑작스러운" },
    { word: "suffer", meaning: "고통을 겪다" },
    { word: "sugar", meaning: "설탕" },
    { word: "suggest", meaning: "제안하다" },
    { word: "suit", meaning: "정장" },
    { word: "summer", meaning: "여름" },
    { word: "sun", meaning: "태양" },
    { word: "Sunday", meaning: "일요일" },
    { word: "sunny", meaning: "맑은" },
    { word: "supper", meaning: "저녁 식사" },
    { word: "supply", meaning: "공급" },
    { word: "support", meaning: "지원" },
    { word: "suppose", meaning: "가정하다" },
    { word: "sure", meaning: "확실한" },
    { word: "surface", meaning: "표면" },
    { word: "surprise", meaning: "놀라게 하다" },
    { word: "swallow", meaning: "삼키다" },
    { word: "swan", meaning: "백조" },
    { word: "swear", meaning: "맹세하다" },
    { word: "sweat", meaning: "땀" },
    { word: "sweater", meaning: "스웨터" },
    { word: "sweep", meaning: "청소하다" },
    { word: "sweet", meaning: "달콤한" },
    { word: "swim", meaning: "수영하다" },
    { word: "swing", meaning: "그네" },
    { word: "sword", meaning: "칼" },
    { word: "symbol", meaning: "상징" },
    { word: "sympathy", meaning: "동정" },
    { word: "system", meaning: "체계" },
    { word: "table", meaning: "테이블" },
    { word: "tail", meaning: "꼬리" },
    { word: "tailor", meaning: "재단사" },
    { word: "take", meaning: "가지다" },
    { word: "talk", meaning: "이야기하다" },
    { word: "tall", meaning: "키가 큰" },
    { word: "tame", meaning: "온순한" },
    { word: "tap", meaning: "물주머니" },
    { word: "taste", meaning: "맛" },
    { word: "tax", meaning: "세금" },
    { word: "tea", meaning: "차" },
    { word: "teach", meaning: "가르치다" },
    { word: "team", meaning: "팀" },
    { word: "tear", meaning: "눈물" },
    { word: "tease", meaning: "놀리다" },
    { word: "telephone", meaning: "전화기" },
    { word: "television", meaning: "텔레비전" },
    { word: "tell", meaning: "말하다" },
    { word: "ten", meaning: "열" },
    { word: "tent", meaning: "텐트" },
    { word: "term", meaning: "기간" },
    { word: "terrible", meaning: "끔찍한" },
    { word: "test", meaning: "시험" },
    { word: "than", meaning: "보다" },
    { word: "thank", meaning: "감사하다" },
    { word: "that", meaning: "저것" },
    { word: "the", meaning: "그" },
    { word: "their", meaning: "그들의" },
    { word: "them", meaning: "그들을" },
    { word: "themselves", meaning: "그들 자신" },
    { word: "then", meaning: "그럼에도" },
    { word: "there", meaning: "거기에" },
    { word: "therefore", meaning: "그러므로" },
    { word: "these", meaning: "이것들" },
    { word: "they", meaning: "그들은" },
    { word: "thick", meaning: "두꺼운" },
    { word: "thin", meaning: "얇은" },
    { word: "thing", meaning: "물건" },
    { word: "think", meaning: "생각하다" },
    { word: "third", meaning: "세 번째" },
    { word: "thirsty", meaning: "목마른" },
    { word: "thirteen", meaning: "십삼" },
    { word: "thirty", meaning: "서른" },
    { word: "this", meaning: "이것" },
    { word: "those", meaning: "저것들" },
    { word: "though", meaning: "~에도 불구하고" },
    { word: "thousand", meaning: "천" },
    { word: "thread", meaning: "실" },
    { word: "threat", meaning: "위협" },
    { word: "three", meaning: "셋" },
    { word: "threw", meaning: "던졌다" },
    { word: "throat", meaning: "목" },
    { word: "through", meaning: "통하여" },
    { word: "throw", meaning: "던지다" },
    { word: "thumb", meaning: "엄지손가락" },
    { word: "thunder", meaning: "천둥" },
    { word: "Thursday", meaning: "목요일" },
    { word: "ticket", meaning: "티켓" },
    { word: "tie", meaning: "매다" },
    { word: "tight", meaning: "딱" },
    { word: "till", meaning: "~까지" },
    { word: "time", meaning: "시간" },
    { word: "tin", meaning: "주철" },
    { word: "tiny", meaning: "아주 작은" },
    { word: "tip", meaning: "팁" },
    { word: "tire", meaning: "타이어" },
    { word: "tired", meaning: "피곤한" },
    { word: "title", meaning: "제목" },
    { word: "to", meaning: "~로" },
    { word: "tobacco", meaning: "담배" },
    { word: "today", meaning: "오늘" },
    { word: "toe", meaning: "발가락" },
    { word: "together", meaning: "함께" },
    { word: "tomato", meaning: "토마토" },
    { word: "tomorrow", meaning: "내일" },
    { word: "tongue", meaning: "혀" },
    { word: "tonight", meaning: "오늘밤" },
    { word: "too", meaning: "너무" },
    { word: "tool", meaning: "도구" },
    { word: "tooth", meaning: "이빨" },
    { word: "top", meaning: "꼭대기" },
    { word: "toss", meaning: "던지다" },
    { word: "touch", meaning: "만지다" },
    { word: "toward", meaning: "~쪽으로" },
    { word: "tower", meaning: "탑" },
    { word: "town", meaning: "마을" },
    { word: "toy", meaning: "장난감" },
    { word: "track", meaning: "추적하다" },
    { word: "trade", meaning: "거래" },
    { word: "train", meaning: "기차" },
    { word: "tramp", meaning: "투전사" },
    { word: "trap", meaning: "덫" },
    { word: "travel", meaning: "여행" },
    { word: "tray", meaning: "쟁반" },
    { word: "treasure", meaning: "보물" },
    { word: "treat", meaning: "대접하다" },
    { word: "tree", meaning: "나무" },
    { word: "trick", meaning: "속임수" },
    { word: "trip", meaning: "여행" },
    { word: "trot", meaning: "속보" },
    { word: "trouble", meaning: "고민" },
    { word: "trousers", meaning: "바지" },
    { word: "truck", meaning: "트럭" },
    { word: "true", meaning: "진실한" },
    { word: "trust", meaning: "신뢰" },
    { word: "truth", meaning: "진실" },
    { word: "try", meaning: "시도하다" },
    { word: "tub", meaning: "통" },
    { word: "Tuesday", meaning: "화요일" },
    { word: "tune", meaning: "곡" },
    { word: "turn", meaning: "돌다" },
    { word: "twelve", meaning: "열두" },
    { word: "twenty", meaning: "스물" },
    { word: "twice", meaning: "두 번" },
    { word: "twig", meaning: "가지" },
    { word: "twin", meaning: "쌍둥이" },
    { word: "twist", meaning: "꼬이다" },
    { word: "two", meaning: "둘" },
    { word: "ugly", meaning: "추한" },
    { word: "umbrella", meaning: "우산" },
    { word: "uncle", meaning: "삼촌" },
    { word: "under", meaning: "아래에" },
    { word: "underneath", meaning: "아래에" },
    { word: "understand", meaning: "이해하다" },
    { word: "union", meaning: "연합" },
    { word: "unit", meaning: "단위" },
    { word: "unite", meaning: "단합하다" },
    { word: "universe", meaning: "우주" },
    { word: "unkind", meaning: "친절하지 못한" },
    { word: "unknown", meaning: "알려지지 않은" },
    { word: "unless", meaning: "~이 아닌 한" },
    { word: "until", meaning: "~까지" },
    { word: "up", meaning: "위로" },
    { word: "upon", meaning: "~위에" },
    { word: "upper", meaning: "상단의" },
    { word: "upset", meaning: "화난" },
    { word: "upside", meaning: "위아래로" },
    { word: "upstairs", meaning: "위층에" },
    { word: "upward", meaning: "위로" },
    { word: "us", meaning: "우리를" },
    { word: "use", meaning: "사용하다" },
    { word: "used", meaning: "사용된" },
    { word: "useful", meaning: "유용한" },
    { word: "valley", meaning: "골짜기" },
    { word: "valuable", meaning: "값진" },
    { word: "value", meaning: "가치" },
    { word: "vapour", meaning: "증기" },
    { word: "variety", meaning: "다양성" },
    { word: "various", meaning: "다양한" },
    { word: "vase", meaning: "꽃병" },
    { word: "vegetable", meaning: "채소" },
    { word: "very", meaning: "매우" },
    { word: "vessel", meaning: "선박" },
    { word: "victory", meaning: "승리" },
    { word: "view", meaning: "전망" },
    { word: "village", meaning: "마을" },
    { word: "visit", meaning: "방문하다" },
    { word: "voice", meaning: "목소리" },
    { word: "vote", meaning: "투표" },
    { word: "wage", meaning: "임금" },
    { word: "waist", meaning: "허리" },
    { word: "wait", meaning: "기다리다" },
    { word: "waiter", meaning: "웨이터" },
    { word: "wake", meaning: "깨다" },
    { word: "walk", meaning: "걷다" },
    { word: "wall", meaning: "벽" },
    { word: "want", meaning: "원하다" },
    { word: "war", meaning: "전쟁" },
    { word: "warm", meaning: "따뜻한" },
    { word: "warn", meaning: "경고하다" },
    { word: "was", meaning: "였다" },
    { word: "wash", meaning: "씻다" },
    { word: "waste", meaning: "낭비" },
    { word: "watch", meaning: "보다" },
    { word: "water", meaning: "물" },
    { word: "waterfall", meaning: "폭포" },
    { word: "wave", meaning: "파도" },
    { word: "wax", meaning: "밀랍" },
    { word: "way", meaning: "방법" },
    { word: "we", meaning: "우리" },
    { word: "weak", meaning: "약한" },
    { word: "weakness", meaning: "약점" },
    { word: "wealth", meaning: "부" },
    { word: "weapon", meaning: "무기" },
    { word: "wear", meaning: "입다" },
    { word: "weather", meaning: "날씨" },
    { word: "web", meaning: "거미줄" },
    { word: "wedding", meaning: "결혼식" },
    { word: "Wednesday", meaning: "수요일" },
    { word: "week", meaning: "주" },
    { word: "weekend", meaning: "주말" },
    { word: "weep", meaning: "울다" },
    { word: "weigh", meaning: "무게를 재다" },
    { word: "weight", meaning: "무게" },
    { word: "welcome", meaning: "환영" },
    { word: "well", meaning: "잘" },
    { word: "west", meaning: "서쪽" },
    { word: "wet", meaning: "젖은" },
    { word: "whale", meaning: "고래" },
    { word: "what", meaning: "무엇" },
    { word: "whatever", meaning: "아무거나" },
    { word: "wheat", meaning: "밀" },
    { word: "wheel", meaning: "바퀴" },
    { word: "when", meaning: "언제" },
    { word: "whenever", meaning: "언제든지" },
    { word: "where", meaning: "어디" },
    { word: "wherever", meaning: "어디든지" },
    { word: "whether", meaning: "~인지" },
    { word: "which", meaning: "어느" },
    { word: "while", meaning: "~동안" },
    { word: "whisper", meaning: "속삭이다" },
    { word: "whistle", meaning: "휘파람" },
    { word: "white", meaning: "흰" },
    { word: "who", meaning: "누구" },
    { word: "whoever", meaning: "누구든지" },
    { word: "whole", meaning: "전체" },
    { word: "whom", meaning: "누구를" },
    { word: "whose", meaning: "누구의" },
    { word: "why", meaning: "왜" },
    { word: "wicked", meaning: "사악한" },
    { word: "wide", meaning: "넓은" },
    { word: "widow", meaning: "미망인" },
    { word: "widower", meaning: "미망인" },
    { word: "width", meaning: "너비" },
    { word: "wife", meaning: "아내" },
    { word: "wild", meaning: "야생의" },
    { word: "will", meaning: "의지" },
    { word: "willing", meaning: "자발적인" },
    { word: "win", meaning: "이기다" },
    { word: "wind", meaning: "바람" },
    { word: "window", meaning: "창문" },
    { word: "wine", meaning: "와인" },
    { word: "wing", meaning: "날개" },
    { word: "winter", meaning: "겨울" },
    { word: "wipe", meaning: "닦다" },
    { word: "wire", meaning: "선" },
    { word: "wise", meaning: "지혜로운" },
    { word: "wish", meaning: "원하다" },
    { word: "with", meaning: "함께" },
    { word: "within", meaning: "~안에" },
    { word: "without", meaning: "~없이" },
    { word: "wolf", meaning: "늑대" },
    { word: "woman", meaning: "여자" },
    { word: "women", meaning: "여자들" },
    { word: "won", meaning: "원" },
    { word: "wonder", meaning: "궁금해하다" },
    { word: "wonderful", meaning: "멋진" },
    { word: "wood", meaning: "나무" },
    { word: "wooden", meaning: "나무의" },
    { word: "wool", meaning: "양모" },
    { word: "word", meaning: "말" },
    { word: "work", meaning: "일" },
    { word: "worker", meaning: "근로자" },
    { word: "world", meaning: "세계" },
    { word: "worm", meaning: "벌레" },
    { word: "worry", meaning: "걱정" },
    { word: "worse", meaning: "더 나쁜" },
    { word: "worship", meaning: "숭배" },
    { word: "worst", meaning: "최악의" },
    { word: "worth", meaning: "가치" },
    { word: "would", meaning: "일 것이다" },
    { word: "wound", meaning: "상처" },
    { word: "wrap", meaning: "싸다" },
    { word: "write", meaning: "쓰다" },
    { word: "wrong", meaning: "잘못된" },
    { word: "yard", meaning: "마당" },
    { word: "year", meaning: "년" },
    { word: "yellow", meaning: "노란" },
    { word: "yes", meaning: "예" },
    { word: "yesterday", meaning: "어제" },
    { word: "yet", meaning: "아직도" },
    { word: "you", meaning: "당신" },
    { word: "young", meaning: "젊은" },
    { word: "your", meaning: "당신의" },
    { word: "yourself", meaning: "당신 자신" },
    { word: "youth", meaning: "젊은이" },
    { word: "zebra", meaning: "얼룩말" },
    { word: "zero", meaning: "영" },
    { word: "zip", meaning: "지퍼" },
    { word: "zoo", meaning: "동물원" }
];

let isFlipped = false;
let knownWords = new Set(); // 아는 단어를 저장할 Set 선언
let isButtonDisabled = false; // 버튼 비활성화 여부를 나타내는 변수

function showRandomWord() {
  let remainingWordsCount = 800 - knownWords.size; // 남아 있는 단어 수 계산
  document.getElementById(
    "remaining-words-count"
  ).textContent = remainingWordsCount; // HTML에 표시

  const remainingWordsArray = words.filter(
    (wordObj) => !knownWords.has(wordObj.word)
  ); // 아는 단어를 제외한 배열 생성
  const randomIndex = Math.floor(Math.random() * remainingWordsArray.length); // 아는 단어를 제외한 배열에서 랜덤한 인덱스 선택
  const randomWordObj = remainingWordsArray[randomIndex]; // 선택된 단어 객체

  front.innerHTML = randomWordObj.word; // 랜덤한 단어 표시
  back.innerHTML = randomWordObj.meaning; // 랜덤한 단어의 뜻 표시
}

showRandomWord(); // 페이지 로딩시 랜덤한 단어와 뜻 표시

flashcard.addEventListener("click", () => {
  if (!isFlipped) {
    flashcard.classList.add("active");
    isFlipped = true;
  } else {
    showRandomWord(); // 클릭할 때마다 랜덤한 단어와 뜻 표시
    flashcard.classList.remove("active");
    isFlipped = false;
  }
});

document.addEventListener("keydown", (event) => {
  if (event.key === "ArrowRight" && !isFlipped) {
    showRandomWord(); // 방향키 입력시 랜덤한 단어와 뜻 표시
    flashcard.classList.add("active");
    isFlipped = true;
  } else if (event.key === "ArrowRight" && isFlipped) {
    showRandomWord(); // 방향키 입력시 랜덤한 단어와 뜻 표시
    flashcard.classList.remove("active");
    isFlipped = false;
  }
});

// '아는 단어' 버튼 클릭 이벤트 리스너
document.getElementById("toggle-checkbox").addEventListener("click", () => {
  if (!isButtonDisabled && !knownWords.has(front.textContent)) {
    knownWords.add(front.textContent); // 아는 단어 Set에 추가
    updateRemainingWordsCount(); // 남아 있는 단어 수 업데이트
    disableButtonForAWhile(); // 일정 시간 동안 버튼 비활성화
  }
});

// 남아 있는 단어 수 업데이트 함수
function updateRemainingWordsCount() {
  let remainingWordsCount = 800 - knownWords.size; // 남아 있는 단어 수 계산
  document.getElementById(
    "remaining-words-count"
  ).textContent = remainingWordsCount; // HTML에 표시
}

// 일정 시간 동안 버튼 비활성화 함수
function disableButtonForAWhile() {
  isButtonDisabled = true;
  document.getElementById("toggle-checkbox").disabled = true;
  setTimeout(() => {
    isButtonDisabled = false;
    document.getElementById("toggle-checkbox").disabled = false;
  }, 1000); // 1초 동안 버튼 비활성화
}